apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadlpzf1456-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadlpzf1456-tenant-component
    app.kubernetes.io/part-of: loadlpzf1456-tenant-app
  name: loadlpzf1456-tenant-component
  namespace: loadlpzf1456-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadlpzf1456-tenant-component
    weight: null
status: {}
